### ISSUE TITLE
Uppercase 'AM' and 'PM' not recognized.

### ISSUE THREAD

**Issue by pherna06** [mrmelon54/WhatsAppExportViewer-v0#1]
App seems not to recognize WhatsApp exported files with times  where AM and PM are uppercase.
Simply running a replace ('AM','PM -> 'am','pm') with a text editor fixes the file, but maybe would be useful to add uppercase format for users with lower knowledge for doing that.

Example of not recognized line:
8/19/21, 12:27 PM - Friend A: Hi, there

**Comment by mrmelon54** [comment]
I fixed this along with adding automatic builds (so I don't have to manually build lol)
